### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by AntoineCRVI** [stuxbet/Fanuc_RMI_API#1]
There is no license in the repository.

The code in this library could be useful for us but without a license we can't use it.

Could you please add a license file to the repository ?

Here are instructions on how to add a license : https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by stuxbet** [comment]
this repo has been moved under the vertec business profile. here is the link to the updated code with a license 
https://github.com/[vertec-io/Fanuc_RMI_API](https://github.com/vertec-io/Fanuc_RMI_API)

**Comment by vertec-io** [comment]
Here is a corrected link [Fanuc_RMI_API](https://github.com/vertec-io/Fanuc_RMI_API). @AntoineCRVI are you looking to potentially contribute to this work? We haven't created a discord group yet but if interested we could spin one up.

**Comment by AntoineCRVI** [comment]
Thank you. Maybe you could add that link to the readme of this repo.

If we do use Fanuc_RMI_API and make improvements to it, we would contribute our improvements.

**Comment by stuxbet** [comment]
just added a link thank you
